
[[Dynamic-ArithmeticException]]
# ArithmeticException
:concept: Dynamic/ArithmeticException

.Synopsis
An arihmetic error occurred

.Syntax
`data RunTimeException = ArithmeticException(str message);`

.Types

.Function
`data RunTimeException = ArithmeticException(str message);`
       
.Usage
import Exception;

.Description
This error is generated when an illegal arithmetic operation occurs or when
a numeric function  is called with an out-of-range argument.

Remedies:

*  Check the validity of the argument before you call the function or apply the operator.
*  Catch the `ArithmeticException` yourself, see link:{RascalLang}#Statements-TryCatch[try catch] statement.

.Examples
[source,rascal-shell-error]
----
----
Division by 0 gives an error:
[source,rascal-shell-error]
----
rascal>3/0;
ArithmeticException("/ by zero") at |test-modules:///ConsoleInput.rsc|(36,3,<3,15>,<3,18>)
Call stack (most recent first):
	main([]) at |test-modules:///ConsoleInput.rsc|(36,3,<3,15>,<3,18>)

ok
----
Giving an out-of-range argument to a mathematical function also gives an error:
[source,rascal-shell-error]
----
rascal>import util::Math;
ok
rascal>tan(-550000000000000000000000);
ArithmeticException("x should be between -(pi/2) and (pi/2)")
Call stack (most recent first):
	tan(-550000000000000000000000, {}) at |std:///util/Math.rsc|(9291,261,<526,0>,<542,28>)
	main([]) at |test-modules:///ConsoleInput.rsc|(55,30,<4,15>,<4,45>)

ok
----
We can also catch the `ArithmeticException` error. First import the Rascal exceptions (which are also included in `Prelude`)
and `IO`:
[source,rascal-shell-error]
----
rascal>import Exception;
ok
rascal>import IO;
ok
rascal>try println(3/0); catch ArithmeticException(msg): println("The message is: <msg>");
The message is: / by zero
ok
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1